export const productData = [
  {
    id: 1,
    name: 'Trenton Sofa',
    title: 'Trenton modular sofa_3',
    description: 'The Trenton modular sofa is perfect for modern living rooms. Its modular design offers flexibility for any space, while the comfortable cushions and sleek style make it a cozy addition to your home.',
    src: '/images/sofa.png',
    price: '25,000.00',
    sku: 'ss01',
    category: 'sofas',
    tags: 'home, sofa, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 2,
    name: 'Granite Dining Set',
    title: 'Granite dining table with dining chair',
    description: 'A beautiful granite dining table with matching chairs that offers both elegance and durability. It’s the perfect centerpiece for any dining room, combining comfort with modern style.',
    src: '/images/dining.png',
    price: '25,000.00',
    sku: 'ds01',
    category: 'dining',
    tags: 'home, dining, table, chair, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 3,
    name: 'Outdoor Bar Set',
    title: 'Outdoor bar table and stool',
    description: 'Ideal for outdoor entertaining, this bar table and stool set adds style and comfort to your patio or garden. Made from weather-resistant materials, it’s perfect for long-lasting outdoor use.',
    src: '/images/table.png',
    price: '25,000.00',
    sku: 'ob01',
    category: 'outdoor',
    tags: 'home, bar, table, stool, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 4,
    name: 'Teak Console',
    title: 'Plain console with teak mirror',
    description: 'A sleek teak console table paired with a matching mirror. This timeless piece adds elegance to any room while providing functional storage space.',
    src: '/images/mirror.png',
    price: '25,000.00',
    sku: 'tc01',
    category: 'furniture',
    tags: 'home, console, mirror, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 5,
    name: 'Grain Coffee Table',
    title: 'Grain coffee table',
    description: 'This simple coffee table, with its natural wood grain finish, adds a rustic touch to your living room while offering a sturdy and stylish surface for everyday use.',
    src: '/images/shop5.png',
    price: '15,000.00',
    sku: 'ct01',
    category: 'tables',
    tags: 'home, coffee table, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 6,
    name: 'Kert Coffee Table',
    title: 'Kert Coffee table',
    description: 'A modern coffee table with a sleek design, perfect for any contemporary living room. The Kert coffee table combines luxury with practicality, providing ample surface area for drinks and décor.',
    src: '/images/shop6.png',
    price: '225,000.00',
    sku: 'kc01',
    category: 'tables',
    tags: 'home, coffee table, luxury, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 7,
    name: 'Rounded Coffee Table',
    title: 'Rounded coffee table_color 2',
    description: 'This rounded coffee table brings a soft, modern touch to your living space. Its simple yet elegant design blends with any décor, offering both style and functionality.',
    src: '/images/shop7.png',
    price: '251,000.00',
    sku: 'rc01',
    category: 'tables',
    tags: 'home, coffee table, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 8,
    name: 'Teak Coffee Table',
    title: 'Reclaimed teack coffee table',
    description: 'Crafted from reclaimed teak wood, this eco-friendly coffee table offers a unique rustic appeal with every piece having its own character and charm.',
    src: '/images/shop8.png',
    price: '25,200.00',
    sku: 'tc02',
    category: 'tables',
    tags: 'home, coffee table, eco-friendly, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 9,
    name: 'Console Table',
    title: 'Plain console_',
    description: 'This minimalist console table is ideal for entryways, living rooms, or bedrooms. Its clean lines provide a simple yet stylish solution for extra storage or display space.',
    src: '/images/shop9.png',
    price: '258,200.00',
    sku: 'pc01',
    category: 'furniture',
    tags: 'home, console, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 10,
    name: 'Teak Sideboard',
    title: 'Reclaimed teack SideBoard',
    description: 'This reclaimed teak sideboard offers ample storage while adding a rustic charm to your living or dining room. It’s the perfect blend of form and function.',
    src: '/images/shop10.png',
    price: '20,000.00',
    sku: 'sb01',
    category: 'furniture',
    tags: 'home, sideboard, eco-friendly, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 11,
    name: 'SJP Chair',
    title: 'SJP _0825',
    description: 'This ergonomic chair combines modern design with comfort, making it a great addition to both home and office settings. Its sleek look and support ensure you sit comfortably throughout the day.',
    src: '/images/shop11.png',
    price: '200,000.00',
    sku: 'sjp01',
    category: 'chairs',
    tags: 'home, chair, office, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 12,
    name: 'Bella Dining Set',
    title: 'Bella Chair and table',
    description: 'A stylish dining set that brings elegance to your home. The Bella dining table, paired with comfortable chairs, creates a sophisticated space for family gatherings and entertaining guests.',
    src: '/images/shop12.png',
    price: '100,000.00',
    sku: 'bd01',
    category: 'dining',
    tags: 'home, dining, chair, table, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 13,
    name: 'Granite Side Table',
    title: 'Granite square side table',
    description: 'This granite side table is the perfect mix of durability and elegance. Its sturdy design and modern aesthetic make it a great addition to any room as an accent piece.',
    src: '/images/shop13.png',
    price: '258,800.00',
    sku: 'gst01',
    category: 'tables',
    tags: 'home, side table, granite, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 14,
    name: 'Asgaard Sofa',
    title: 'Asgaard Sofa',
    description: 'The Asgaard sofa offers comfort and modern design, making it an excellent choice for a contemporary living room. It’s designed to provide both style and relaxation.',
    src: '/images/shop14.png',
    price: '25,000.00',
    sku: 'as01',
    category: 'sofas',
    tags: 'home, sofa, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 15,
    name: 'Maya Sofa',
    title: 'Maya sofa three seator',
    description: 'The Maya three-seater sofa is designed to bring comfort and elegance to your living room. With its luxurious upholstery and modern style, it’s the perfect addition to any home.',
    src: '/images/shop15.png',
    price: '115,000.00',
    sku: 'ms01',
    category: 'sofas',
    tags: 'home, sofa, shop',
    quantity: 1  // Added quantity property
  },
  {
    id: 16,
    name: 'Outdoor Sofa Set',
    title: 'Outdoor sofa set',
    description: 'Perfect for outdoor relaxation, this sofa set combines comfort with durability. Ideal for patios and gardens, it’s made from weather-resistant materials, ensuring it will last for years.',
    src: '/images/shop5.png',
    price: '244,000.00',
    sku: 'os01',
    category: 'outdoor',
    tags: 'home, sofa, outdoor, shop',
    quantity: 1  // Added quantity property
  }
];
